### ISSUE TITLE
Lime project detection is too naive

### ISSUE THREAD

**Issue by EliteMasterEric** [openfl/lime-vscode-extension#103]
I am working on a project called PickHaxe, for developing Minecraft mods using Haxe.

I opted to include workspace parameters in a `project.xml` file, which works great, but causes issues as the Lime extension complains that the project configuration is invalid.

I use a different top-level XML tag for my projects, so ideally that could be used for detection.

**Comment by player-03** [comment]
Can you post the problem parameters?

**Comment by EliteMasterEric** [comment]
Here is an example of what a PickHaxe `project.xml` looks like:

https://github.com/EliteMasterEric/PickHaxe-Samples/blob/master/madeinhaxe/project.xml

**Comment by player-03** [comment]
Oh, I see what you're saying. You want to make it stop detecting (and thus complaining about) these files, because they were never meant to have anything to do with Lime. Fair enough.

With Lime itself you can specify a custom path and then it'll ignore project.xml, so maybe the extension should offer the same option.

**Comment by joshtynjala** [comment]
> With Lime itself you can specify a custom path and then it'll ignore project.xml, so maybe the extension should offer the same option.

There's a `lime.projectFile` setting in lime-vscode-extension. That should do it.
