### ISSUE TITLE
Error Lime

### ISSUE THREAD

**Issue by NotSomeBlox** [openfl/lime-vscode-extension#107]
![lIME Error](https://github.com/openfl/lime-vscode-extension/assets/104321099/ee09a266-9fd8-40f3-827f-5c6208894593)
This happened when loading VS Code when loading a project containing Haxe code

**Comment by player-03** [comment]
What version of Flixel do you have installed? You can try `haxelib path flixel:5.2.2` to see if you have 5.2.2.

**Comment by NotSomeBlox** [comment]
5.5.0

**Comment by NotSomeBlox** [comment]
Still shows the error even after what you said to do

**Comment by NotSomeBlox** [comment]
![image](https://github.com/openfl/lime-vscode-extension/assets/104321099/d1a29acd-5772-434d-8651-f1855382777f)
Here's the popup with the error, also it still shows up

**Comment by joshtynjala** [comment]
I'm guessing that your project.xml specifies flixel 5.2.2 like this:

```xml
<haxelib name="flixel" version="5.2.2" />
```

You have flixel 5.5.0, though. So you have the wrong version installed.

You have two options:

1) Install flixel 5.2.2 with haxelib install flixel 5.2.2
2) Change your project.xml to specify 5.5.0 instead of 5.2.2.

I don't know which one is right for your needs, but either one should fix that particular error.
