### ISSUE TITLE
Add 'electron' target

### ISSUE THREAD

**Issue by TomByrne** [openfl/lime-vscode-extension#48]
Would be great if you could add the electron target.
I know it's possible to add in `openfl.lime-vscode-extension-1.2.1\bin\lime-vscode.js`, but would be great if you could add by default.

**Comment by Gama11** [comment]
@jgranick Should this be part of the UI by default, or is it the target too young / untested for that (assuming that's the reason why it hasn't been added thus far)?

Beyond that, we might need a setting for "custom targets", e.g. for people wanting to test the HL target with a Lime from source rebuilt for HL support.

**Comment by jgranick** [comment]
The plan was for Lime to automatically provide the targets available, though with target aliases, this is perhaps a little more complicated.

In theory, it would be nice for `lime display project.xml --targets` to know if you have `lime-switch` installed and can target Nintendo, for example. Perhaps this is too fancy

Otherwise we would add targets like Switch or Electron, and get developers who wonder why they might not work

**Comment by Gama11** [comment]
Sure, but Electron is not one of those targets, is it? It's shipped by default with Lime?

**Comment by Gama11** [comment]
I guess it still could be confusing for people using older Lime versions that didn't support it yet.

**Comment by jgranick** [comment]
Current dev supports Electron and allows support for adding new targets using settings
