### ISSUE TITLE
Cannot find "Project.xml" file

### ISSUE THREAD

**Issue by alxtford** [openfl/lime-vscode-extension#74]
Hi,Running the extension out the box results in this error:
`Error: You must have a "project.xml" file or specify another valid project file when using the 'test' command`

I am using a template, with `Project.xml` in the root folder. The project correctly runs in Chrome when using `lime test html5` on the cmd line

**Comment by RinkaGI** [comment]
Same, idk why, i have all components c++, haxe, all haxeflixel libraries, and i'm using template from vs code and the vs code terminal, and i have that error

sorry for bad english

**Comment by joshtynjala** [comment]
I wonder if it can happen because _Project.xml_ has a capital **P**, and it's looking for _project.xml_ with a lower-case **p**. Some file systems are case-insensitive, so it wouldn't matter in those cases. However, if your file system is case-senstive, the case of the letter P in the name would certainly matter.

Anyway, this issue is a few years old now, so I'm going to close it.
